universe		         = vanilla
executable             	 = one_matrix_main.py
log                    	 = onematrix.log
arguments		         = /lustre/fs24/group/cqta/bvarol/workspace/matrixmodels/results/run03_pauli.dipf
output                 	 = onematrix_
error                  	 = onematrixerror
should_transfer_files  	 = Yes
when_to_transfer_output	 = ON_EXIT
request_memory         	 = 8GB
request_disk           	 = 8GB
+JobFlavour		         = "nextweek"

queue
