universe		         = vanilla
executable             	 =/lustre/fs24/group/cqta/bvarol/workspace/matrixmodels/one_matrix_max_N.py
log                    	 = /lustre/fs24/group/cqta/bvarol/workspace/matrixmodels/submissions/onematrix_1_5.log
arguments		         = /lustre/fs24/group/cqta/bvarol/workspace/matrixmodels/new_results/crankupN7D1g0_1a0_01 
error = error252
should_transfer_files  	 = Yes
when_to_transfer_output	 = ON_EXIT
request_memory         	 = 8GB
request_disk           	 = 8GB
Request_Cpus            = 4
+RequestRuntime = 604700
queue
