universe		         = vanilla
executable             	 =/lustre/fs24/group/cqta/bvarol/workspace/matrixmodels/zcalc.py
log                    	 = /lustre/fs24/group/cqta/bvarol/workspace/matrixmodels/submissions/onematrix_1_523.log

output = outputfile23
error = error25223
should_transfer_files  	 = Yes
when_to_transfer_output	 = ON_EXIT
request_memory         	 = 100MB
request_disk           	 = 100MB
Request_Cpus            = 2
+RequestRuntime = 604700
queue
